### PR TITLE
support python3

### PR DESCRIPTION
**Pull request by heylenz**
python 2.7,  python3.6,  python 3.7  test passed!
not support python34, if want to support python34, i will fixed it!

### CODE REVIEW

**Comment by ababak** [comment]
1. Replacing `unicode` with `str` may break Python 2.7 compatibility.
1. Why do you remove `from __future__ import division`?
1. Why do you convert `keys()`, `values()` and `items()` to lists?

**Comment by heylenz** [comment]
1. i test it  in python2.7, and when i use utf-8 code not break!
2. My idea is to just make sure shotgunEventDaemon.py supports python2 and python3,if i use python27 , i'll add "from __future__ import division" or something other in custom plugin,
3. I used a python tool (2to3.py)  convert the scripts.

**Comment by garyo** [comment]
What's the status of this? Will it be merged? Clock's still ticking... :-)

**Comment by garyo** [comment]
Python 3 doesn't have `email.Utils` since it was renamed to `email.utils` in python 2.7.
This patch fixes that. I'm not sure supporting python2.4 is really needed but I expect this would still work there. Works for me in python 3.7.

```patch
diff --git a/src/shotgunEventDaemon.py b/src/shotgunEventDaemon.py
index d871004..fa26040 100755
--- a/src/shotgunEventDaemon.py
+++ b/src/shotgunEventDaemon.py
@@ -30,6 +30,11 @@ try:
 except ImportError:
     import ConfigParser as configparser
 
+try:
+    import email.utils as emailutils
+except ImportError:
+    import email.Utils as emailutils # for python 2.4 and earlier
+
 import datetime
 import logging
 import logging.handlers
@@ -1099,10 +1104,8 @@ class CustomSMTPHandler(logging.handlers.SMTPHandler):
             socket.setdefaulttimeout(None)
 
         # Mostly copied from Python 2.7 implementation.
-        # Using email.Utils instead of email.utils for 2.4 compat.
         try:
             import smtplib
-            from email.Utils import formatdate
             port = self.mailport
             if not port:
                 port = smtplib.SMTP_PORT
@@ -1113,7 +1116,7 @@ class CustomSMTPHandler(logging.handlers.SMTPHandler):
                             self.fromaddr,
                             ",".join(self.toaddrs),
                             self.getSubject(record),
-                            formatdate(), msg)
+                            emailutils.formatdate(), msg)
             if self.username:
                 if self.secure is not None:
                     smtp.ehlo()

```

**Comment by unquietwiki** [comment]
[pylint-shotgunEvents.txt](https://github.com/shotgunsoftware/shotgunEvents/files/3619911/pylint-shotgunEvents.txt)

I was doing code quality checks on this stuff; Bandit can't even run on the current code base, due to AST errors. This is what PyLint found.

**Comment by unquietwiki** [comment]
[pylint-shotgunEvents.txt](https://github.com/shotgunsoftware/shotgunEvents/files/3624878/pylint-shotgunEvents.txt)

```
pip3 install pylint black trim
trim shotgunEvents
2to3-2.7 -wn shotgunEvents
black shotgunEvents
```

PyLint score went from 2.x to 6.x; it seems a good chunk of the remaining errors have to do with indentation bugs in black & dependencies I didn't have installed on my system right now. I hope this helps.

**Comment by unquietwiki** [comment]
[bandit.txt](https://github.com/shotgunsoftware/shotgunEvents/files/3624888/bandit.txt)

There's the bandit report, now that it can run.

**Comment by pboucher** [comment]
Python 3 support has been implemented with https://github.com/shotgunsoftware/shotgunEvents/pull/73

**Pull request closed without merging**
