### PR TITLE
Bug, bad doc strings, unreachable code

### PR DESCRIPTION
**Pull request by bdeluca**
Hey, I was trying to use the event framework in some code that we are using but out quality tools reject it for a few reasons. Some of the issues were more serious than others, these changes fix things with out changing any particular logic. (except for the bug)

This PR contains 3 changes that I think are useful to accept. 
1 bug
1 bad docstring (referencing arguments that are not there)
1 un reachable peice of code.

### CODE REVIEW

**Comment by kporangehat** [comment]
Thanks Ben,

Looks like some of this was introduced recently in 454846ec1a42bf8ac87b13f00ad6c008450d3fd9. We'll review.

**Comment by AdricEpic** [comment]
I have an [alternative fix in my fork](https://github.com/shotgunsoftware/shotgunEvents/compare/master...AdricEpic:fix_unreachable_code) that re-enables the unreachable code instead of commenting it out.

**Comment by bdeluca** [comment]
That looks like a better fix adric, thanks!

**Comment by neilvictorgrey** [comment]
Thanks for the contrib @bdeluca ; I'm going to close this off in favour of @AdricEpic 's changes in PR's #43 & #51 .

**Pull request closed without merging**
